import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
const ATTENDANCE_UI={
 School:{scope:"Class / Section / Period",session:"Class Period",unit:"Class / Subject",description:"School-wide attendance oversight for class, section and period-based sessions.",select:"Select class period",search:"Search student, class, subject or period..."},
 College:{scope:"Course / Section / Hour",session:"Course Hour",unit:"Course / Section",description:"College-wide attendance oversight for course, section and teaching-hour sessions.",select:"Select course hour",search:"Search student, course, section or hour..."},
 University:{scope:"Course / Cohort / Session",session:"Academic Session",unit:"Course / Cohort",description:"University-wide attendance oversight for course, cohort and scheduled academic sessions.",select:"Select academic session",search:"Search student, course, cohort or session..."},
};
export default function AdminAttendance({ui}){
 const labels=ATTENDANCE_UI[ui?.label]||ATTENDANCE_UI.University;
 const[data,setData]=useState(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("ALL"),[sessionId,setSessionId]=useState(""),[roster,setRoster]=useState(null); const load=()=>api.get("/api/v1/admin/attendance-overview").then(r=>{setData(r.data);setError("")}).catch(e=>setError(e?.response?.data?.detail||"Unable to load attendance.")); useEffect(()=>{load()},[]); const loadRoster=async id=>{setSessionId(id);if(!id){setRoster(null);return}try{const r=await api.get("/api/v1/admin/attendance/"+id);setRoster(r.data);setError("")}catch(e){setError(e?.response?.data?.detail||"Unable to load attendance roster.")}}; const mark=async(sid,student,status,note)=>{try{await api.put("/api/v1/admin/attendance/"+sid,{student_user_id:student,status,note});await loadRoster(sid);load()}catch(e){setError(e?.response?.data?.detail||"Unable to update attendance.")}};
 const rows=useMemo(()=>{if(!data)return[];const q=query.trim().toLowerCase();return data.entries.filter(x=>(status==="ALL"||x.status===status)&&(!q||[x.student_name,x.session_title,x.unit_name,x.note].some(v=>String(v||"").toLowerCase().includes(q))))},[data,query,status]);
 return <div>
  <section className="module-context"><div><span className="eyebrow">{ui.label} • Institution Admin</span><h1>Attendance</h1><p>{labels.description}</p></div></section>
  {error&&<div className="error">{error}</div>}
  {data&&<>
   <div className="module-kpis"><article><small>{labels.scope} Records</small><strong>{data.summary.records}</strong></article><article><small>Present</small><strong>{data.summary.present}</strong></article><article><small>Absent</small><strong>{data.summary.absent}</strong></article><article><small>Late</small><strong>{data.summary.late}</strong></article><article><small>Excused</small><strong>{data.summary.excused}</strong></article><article><small>Attendance Rate</small><strong>{data.summary.attendance_percentage==null?"—":data.summary.attendance_percentage+"%"}</strong></article></div>
   <section className="panel"><div className="panel-title"><b>Manage {labels.session} Attendance</b><span>Institution Admin override with audit trail</span></div><select value={sessionId} onChange={e=>loadRoster(e.target.value)}><option value="">{labels.select}</option>{data.sessions.map(x=><option key={x.id} value={x.id}>{x.title} — {new Date(x.starts_at).toLocaleString()}</option>)}</select>{roster&&<div className="table-scroll"><table><thead><tr><th>Student</th><th>Status</th><th>Note</th><th>Update</th></tr></thead><tbody>{roster.students.length?roster.students.map(x=><tr key={x.student_user_id}><td><b>{x.student_name}</b></td><td>{x.status}</td><td>{x.note||"—"}</td><td>{["PRESENT","ABSENT","LATE","EXCUSED"].map(v=><button key={v} type="button" onClick={()=>mark(roster.session.id,x.student_user_id,v,x.note||"")}>{v}</button>)}</td></tr>):<tr><td colSpan="4" className="empty-cell">No enrolled students found for this session.</td></tr>}</tbody></table></div>}</section>
   <section className="panel structure-table"><div className="panel-title"><b>Attendance Register</b><span>{rows.length} visible records</span></div>
    <div className="form-grid"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={labels.search} /><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{["PRESENT","ABSENT","LATE","EXCUSED"].map(x=><option key={x}>{x}</option>)}</select></div>
    <div className="table-scroll"><table><thead><tr><th>Student</th><th>{labels.unit}</th><th>{labels.session}</th><th>Status</th><th>Note</th><th>Marked</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><b>{x.student_name}</b></td><td>{x.unit_name}</td><td>{x.session_title}</td><td><b>{x.status}</b></td><td>{x.note||"—"}</td><td>{new Date(x.marked_at).toLocaleString()}</td></tr>):<tr><td colSpan="6" className="empty-cell">No attendance records match these filters.</td></tr>}</tbody></table></div>
   </section>
  </>}
 </div>
}
