import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
const TIMETABLE_UI={
 School:{schedule:"Schedule Class Period",session:"Class Period",unit:"Class / Section / Subject",teacher:"Teacher",room:"Classroom / Lab",description:"School timetable across classes, sections, subjects, teachers and classrooms.",unitPlaceholder:"Class / Section / Subject",personPlaceholder:"Teacher",titlePlaceholder:"Period / Subject title",roomPlaceholder:"Classroom / Lab",search:"Search class, section, subject, teacher or room..."},
 College:{schedule:"Schedule Course Hour",session:"Course Hour",unit:"Program / Semester / Course",teacher:"Faculty",room:"Classroom / Lab",description:"College timetable across programs, semesters, courses, faculty and classrooms.",unitPlaceholder:"Program / Semester / Course",personPlaceholder:"Faculty",titlePlaceholder:"Course / Hour title",roomPlaceholder:"Classroom / Lab",search:"Search program, semester, course, faculty or room..."},
 University:{schedule:"Schedule Academic Session",session:"Academic Session",unit:"Program / Cohort / Course",teacher:"Faculty",room:"Lecture Hall / Lab",description:"University timetable across programs, cohorts, courses, faculty and teaching spaces.",unitPlaceholder:"Program / Cohort / Course",personPlaceholder:"Faculty",titlePlaceholder:"Academic session title",roomPlaceholder:"Lecture Hall / Lab",search:"Search program, cohort, course, faculty or room..."},
};
export default function AdminTimetable({ui}){
 const labels=TIMETABLE_UI[ui?.label]||TIMETABLE_UI.University;
 const[data,setData]=useState(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[scope,setScope]=useState("ALL"),[form,setForm]=useState({unit_id:"",teacher_user_id:"",title:"",starts_at:"",ends_at:"",room:""});
 const load=()=>api.get("/api/v1/admin/timetable").then(r=>setData(r.data)).catch(e=>setError(e?.response?.data?.detail||"Unable to load timetable."));
 useEffect(()=>{load()},[]); const createSession=async e=>{e.preventDefault();try{await api.post("/api/v1/admin/timetable",{...form,unit_id:Number(form.unit_id),teacher_user_id:Number(form.teacher_user_id)});setForm({unit_id:"",teacher_user_id:"",title:"",starts_at:"",ends_at:"",room:""});setError("");load()}catch(e){setError(e?.response?.data?.detail||"Unable to schedule class.")}}; const updateSession=async x=>{const status=prompt("Status: Scheduled / Completed / Cancelled",x.status);if(status===null)return;try{await api.put("/api/v1/admin/timetable/"+x.id,{teacher_user_id:x.teacher_id,title:x.title,starts_at:x.starts_at,ends_at:x.ends_at,room:x.room||"",status});load()}catch(e){setError(e?.response?.data?.detail||"Unable to update class session.")}};
 const rows=useMemo(()=>{if(!data)return[];const now=new Date();const q=query.trim().toLowerCase();return data.sessions.filter(x=>(scope==="ALL"||(scope==="UPCOMING"&&new Date(x.ends_at)>=now)||(scope==="PAST"&&new Date(x.ends_at)<now))&&(!q||[x.title,x.unit_name,x.teacher_name,x.room,x.status].some(v=>String(v||"").toLowerCase().includes(q))))},[data,query,scope]);
 return <div>
  <section className="module-context"><div><span className="eyebrow">{ui.label} • Institution Admin</span><h1>Timetable</h1><p>{labels.description}</p></div></section>
  {error&&<div className="error">{error}</div>}
  {data&&<>
   <div className="module-kpis"><article><small>Total {labels.session}s</small><strong>{data.summary.total}</strong></article><article><small>Upcoming</small><strong>{data.summary.upcoming}</strong></article><article><small>{labels.teacher} Scheduled</small><strong>{data.summary.teachers}</strong></article><article><small>{labels.unit}</small><strong>{data.summary.academic_units}</strong></article><article><small>Rooms in Use</small><strong>{data.summary.rooms}</strong></article></div>
   <section className="panel"><div className="panel-title"><b>{labels.schedule}</b><span>{labels.teacher}, academic unit and room conflicts are checked automatically</span></div><form className="form-grid" onSubmit={createSession}><select required value={form.unit_id} onChange={e=>setForm({...form,unit_id:e.target.value})}><option value="">{labels.unitPlaceholder}</option>{data.units.map(x=><option key={x.id} value={x.id}>{x.name} — {x.code}</option>)}</select><select required value={form.teacher_user_id} onChange={e=>setForm({...form,teacher_user_id:e.target.value})}><option value="">{labels.personPlaceholder}</option>{data.teachers.map(x=><option key={x.id} value={x.id}>{x.name} — Campus {x.campus_id}</option>)}</select><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder={labels.titlePlaceholder}/><input required type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/><input required type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/><input value={form.room} onChange={e=>setForm({...form,room:e.target.value})} placeholder={labels.roomPlaceholder}/><button>{labels.schedule}</button></form></section>
   <section className="panel structure-table"><div className="panel-title"><b>Institution Timetable</b><span>{rows.length} visible sessions</span></div>
    <div className="form-grid"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={labels.search} /><select value={scope} onChange={e=>setScope(e.target.value)}><option value="ALL">All sessions</option><option value="UPCOMING">Upcoming</option><option value="PAST">Past</option></select></div>
    <div className="table-scroll"><table><thead><tr><th>{labels.session}</th><th>{labels.unit}</th><th>{labels.teacher}</th><th>Starts</th><th>Ends</th><th>Room</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><b>{x.title}</b></td><td>{x.unit_name}<br/><small>{String(x.unit_type||"").replaceAll("_"," ")}</small></td><td>{x.teacher_name}</td><td>{new Date(x.starts_at).toLocaleString()}</td><td>{new Date(x.ends_at).toLocaleString()}</td><td>{x.room||"TBA"}</td><td>{x.status}</td><td><button type="button" onClick={()=>updateSession(x)}>Update</button></td></tr>):<tr><td colSpan="8" className="empty-cell">No timetable entries match these filters.</td></tr>}</tbody></table></div>
   </section>
  </>}
 </div>
}
