import React,{useEffect,useState} from "react"; import {api} from "../api";
const PARENT_FEE_UI={School:{title:"School Fees",fee:"School Fee",description:"View your child's tuition, term, transport and school fee ledger."},College:{title:"Semester Fees",fee:"College Fee",description:"View the selected student's tuition, semester, exam and laboratory fee ledger."},University:{title:"University Fees",fee:"University Fee",description:"View the selected student's tuition, credit, hostel and academic fee ledger."}};
export default function ParentChildrenFinance({title,ui}){
 const labels=PARENT_FEE_UI[ui?.label]||PARENT_FEE_UI.University;
 const [children,setChildren]=useState([]),[childId,setChildId]=useState(""),[fees,setFees]=useState(null),[receipts,setReceipts]=useState([]),[err,setErr]=useState("");
 useEffect(()=>{api.get("/api/v1/parents/children").then(r=>{setChildren(r.data);if(r.data.length)setChildId(String(r.data[0].id))}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load linked children."))},[]);
 useEffect(()=>{if(title!=="Fees"||!childId)return;api.get("/api/v1/parents/children/"+childId+"/fees").then(r=>{setFees(r.data);setErr("")}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load child fee records."))},[title,childId]);
 if(title==="My Children")return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Parent / Guardian</span><h1>My Children</h1><p>Students officially linked to your parent account.</p></div><div className="hero-badge">{children.length} Linked</div></section>{err&&<div className="error">{err}</div>}<section className="panel structure-table"><div className="table-scroll"><table><thead><tr><th>Student</th><th>Email</th><th>Relationship</th></tr></thead><tbody>{children.length?children.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.email}</td><td>{c.relationship}</td></tr>):<tr><td colSpan="3" className="empty-cell">No students are linked to this parent account.</td></tr>}</tbody></table></div></section></div>;
 const rows=fees?.records||[]; const due=rows.reduce((s,r)=>s+r.amount_due,0),paid=rows.reduce((s,r)=>s+r.amount_paid,0),balance=rows.reduce((s,r)=>s+r.balance,0); const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
 async function showReceipts(id){try{const r=await api.get("/api/v1/fee-ledger/"+id+"/receipts");setReceipts(r.data);setErr("")}catch(e){setErr(e?.response?.data?.detail||"Unable to load receipts.")}}
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Parent / Guardian</span><h1>{labels.title}</h1><p>{labels.description}</p></div><label>Child<select value={childId} onChange={e=>{setChildId(e.target.value);setReceipts([])}}>{children.map(c=><option key={c.id} value={c.id}>{c.name} — {c.relationship}</option>)}</select></label></section>{err&&<div className="error">{err}</div>}<div className="finance-kpis"><article><small>Total Fees</small><strong>{money(due)}</strong></article><article><small>Paid</small><strong>{money(paid)}</strong></article><article><small>Balance</small><strong>{money(balance)}</strong></article></div><section className="panel structure-table"><div className="table-scroll"><table><thead><tr><th>{labels.fee}</th><th>Due</th><th>Paid</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td><b>{r.title}</b><br/><small>{r.fee_code}</small></td><td>{money(r.amount_due)}</td><td>{money(r.amount_paid)}</td><td>{money(r.balance)}</td><td>{r.status}</td><td><button className="table-action" onClick={()=>showReceipts(r.id)}>Receipts</button></td></tr>):<tr><td colSpan="6" className="empty-cell">No fee assignments available.</td></tr>}</tbody></table></div></section>{receipts.length>0&&<section className="panel structure-table"><div className="table-scroll"><table><thead><tr><th>Receipt</th><th>Amount</th><th>Reference</th><th>Paid At</th></tr></thead><tbody>{receipts.map(x=><tr key={x.id}><td>{x.receipt_no}</td><td>{money(x.amount)}</td><td>{x.reference||"—"}</td><td>{new Date(x.paid_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>}</div>
}