import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
import StaffAcademicManagement from "./StaffAcademicManagement";
const STAFF_ROLES=["Teacher","Accounts","HR","Campus Admin","Auditor"];
const STAFF_UI={
 School:{title:"Staff",teaching:"Teachers",assignment:"Teacher Assignments",description:"Manage teachers and school administrative staff accounts."},
 College:{title:"Faculty & Staff",teaching:"Faculty",assignment:"Faculty Assignments",description:"Manage faculty and college administrative staff accounts."},
 University:{title:"Faculty & Staff",teaching:"Faculty",assignment:"Faculty Assignments",description:"Manage faculty and university administrative staff accounts."},
};
export default function StaffManagement({ui}){
 const labels=STAFF_UI[ui?.label]||STAFF_UI.University;
 const [view,setView]=useState("DIRECTORY");
 const [rows,setRows]=useState([]),[query,setQuery]=useState(""),[role,setRole]=useState("ALL"),[error,setError]=useState(""),[message,setMessage]=useState(""),[editing,setEditing]=useState(null),[creating,setCreating]=useState(false),[form,setForm]=useState({name:"",email:"",password:"",role:"Teacher",campus_id:1});
 const load=()=>api.get("/api/v1/users").then(r=>setRows(r.data.filter(x=>STAFF_ROLES.includes(x.role)))).catch(e=>setError(e?.response?.data?.detail||"Unable to load staff."));
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(x=>(x.name+" "+x.email).toLowerCase().includes(query.toLowerCase())&&(role==="ALL"||x.role===role)),[rows,query,role]);
 async function create(e){e.preventDefault();try{setError("");await api.post("/api/v1/users",{...form,campus_id:Number(form.campus_id)});setMessage("Staff account created.");setCreating(false);setForm({name:"",email:"",password:"",role:"Teacher",campus_id:1});await load()}catch(e){setError(e?.response?.data?.detail||"Unable to create staff.")}}
 async function save(e){e.preventDefault();try{setError("");await api.patch("/api/v1/users/"+editing.id,{name:editing.name,role:editing.role,campus_id:Number(editing.campus_id)});setMessage("Staff details updated.");setEditing(null);await load()}catch(e){setError(e?.response?.data?.detail||"Unable to update staff.")}}
 async function toggle(x){if(x.is_active&&!window.confirm("Deactivate this staff account?"))return;try{await api.patch("/api/v1/users/"+x.id,{is_active:!x.is_active});setMessage(x.is_active?"Staff account deactivated.":"Staff account activated.");await load()}catch(e){setError(e?.response?.data?.detail||"Unable to change account status.")}}
 return <div className="workspace-page"><div className="page-heading"><div><span className="eyebrow">Institution Administration</span><h1>{labels.title}</h1><p>{labels.description}</p></div><button className="primary" onClick={()=>setCreating(true)}>Add Staff</button></div><div className="admissions-tabs"><button className={view==="DIRECTORY"?"active":""} onClick={()=>setView("DIRECTORY")}>Staff Directory</button><button className={view==="ACADEMICS"?"active":""} onClick={()=>setView("ACADEMICS")}>{labels.assignment}</button></div>{view==="ACADEMICS"&&<StaffAcademicManagement ui={ui}/>}{view==="DIRECTORY"&&<>{error&&<div className="error-banner">{error}</div>}{message&&<div className="success-banner">{message}</div>}
 <section className="kpi-grid"><div className="kpi-card"><small>Total Staff</small><strong>{rows.length}</strong></div><div className="kpi-card"><small>{labels.teaching}</small><strong>{rows.filter(x=>x.role==="Teacher").length}</strong></div><div className="kpi-card"><small>Active</small><strong>{rows.filter(x=>x.is_active).length}</strong></div><div className="kpi-card"><small>Inactive</small><strong>{rows.filter(x=>!x.is_active).length}</strong></div></section>
 {creating&&<section className="panel"><div className="panel-title"><b>Add Staff</b><button className="table-action" onClick={()=>setCreating(false)}>Cancel</button></div><form className="setup-form" onSubmit={create}><label>Name<input required value={form.name} onChange={e=>setForm(x=>({...x,name:e.target.value}))}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm(x=>({...x,email:e.target.value}))}/></label><label>Temporary Password<input required type="password" minLength="8" value={form.password} onChange={e=>setForm(x=>({...x,password:e.target.value}))}/></label><label>Role<select value={form.role} onChange={e=>setForm(x=>({...x,role:e.target.value}))}>{STAFF_ROLES.map(r=><option key={r}>{r}</option>)}</select></label><label>Campus ID<input required type="number" min="1" value={form.campus_id} onChange={e=>setForm(x=>({...x,campus_id:e.target.value}))}/></label><button className="primary">Create Staff</button></form></section>}
 {editing&&<section className="panel"><div className="panel-title"><b>Edit Staff</b><button className="table-action" onClick={()=>setEditing(null)}>Cancel</button></div><form className="setup-form" onSubmit={save}><label>Name<input required value={editing.name} onChange={e=>setEditing(x=>({...x,name:e.target.value}))}/></label><label>Role<select value={editing.role} onChange={e=>setEditing(x=>({...x,role:e.target.value}))}>{STAFF_ROLES.map(r=><option key={r}>{r}</option>)}</select></label><label>Campus ID<input required type="number" min="1" value={editing.campus_id} onChange={e=>setEditing(x=>({...x,campus_id:e.target.value}))}/></label><button className="primary">Save Changes</button></form></section>}
 <section className="panel"><div className="panel-title"><b>Staff Directory</b><span>{filtered.length} shown</span></div><div className="toolbar"><input className="search-input" placeholder="Search staff" value={query} onChange={e=>setQuery(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option value="ALL">All roles</option>{STAFF_ROLES.map(r=><option key={r}>{r}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>Staff Member</th><th>Role</th><th>Campus</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.length?filtered.map(x=><tr key={x.id}><td><strong>{x.name}</strong><br/><small>{x.email}</small></td><td>{x.role}</td><td>{x.campus_id}</td><td>{x.is_active?"Active":"Inactive"}</td><td><button className="table-action" onClick={()=>setEditing({...x})}>Edit</button> <button className="table-action" onClick={()=>toggle(x)}>{x.is_active?"Deactivate":"Activate"}</button></td></tr>):<tr><td colSpan="5" className="empty-cell">No staff found.</td></tr>}</tbody></table></div></section></>}
</div>
}