import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
const ADMISSION_LABELS={
 School:{program:"Grade / Academic Term",section:"Class / Section",courses:"Subjects",guardian:"Parent / Guardian",assignment:"Class / Academic Assignment",missing:"Without Class / Section"},
 College:{program:"Program / Semester",section:"Section / Batch",courses:"Courses / Subjects",guardian:"Parent / Guardian",assignment:"Program / Semester Assignment",missing:"{labels.missing}"},
 University:{program:"Degree Program / Semester",section:"Cohort / Section",courses:"Courses / Credits",guardian:"Guardian / Emergency Contact",assignment:"Program / Course Assignment",missing:"Without Cohort / Section"},
};
export default function StudentEnrollment({ui}){
 const [units,setUnits]=useState([]),[users,setUsers]=useState([]),[students,setStudents]=useState([]),[query,setQuery]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[historyStudent,setHistoryStudent]=useState(null),[history,setHistory]=useState([]),[historyLoading,setHistoryLoading]=useState(false),[profile,setProfile]=useState(null),[profileLoading,setProfileLoading]=useState(false),[summary,setSummary]=useState({total:0,active:0,withdrawn:0,without_section:0,without_guardian:0}),[qualityFilter,setQualityFilter]=useState("ALL"),[guardianDraft,setGuardianDraft]=useState({}),[admissionView,setAdmissionView]=useState("DASHBOARD");
 const labels=ADMISSION_LABELS[ui?.label]||ADMISSION_LABELS.University;
 const [form,setForm]=useState({name:"",email:"",password:"",campus_id:1,program_unit_id:"",section_unit_id:"",course_unit_ids:[],parent_user_id:"",relationship:"Guardian"});
 const loadStudents=()=>Promise.all([api.get("/api/v1/admissions/students"),api.get("/api/v1/admissions/summary")]).then(([s,m])=>{setStudents(s.data);setSummary(m.data)});
 useEffect(()=>{Promise.all([api.get("/api/v1/academic-structure"),api.get("/api/v1/users"),api.get("/api/v1/admissions/students"),api.get("/api/v1/admissions/summary")]).then(([a,u,s,m])=>{setUnits(a.data);setUsers(u.data);setStudents(s.data);setSummary(m.data)}).catch(e=>setError(e?.response?.data?.detail||"Unable to load enrollment data."))},[]);
 const programs=useMemo(()=>units.filter(x=>["PROGRAM","ACADEMIC_PERIOD"].includes(x.unit_type)),[units]),sections=useMemo(()=>units.filter(x=>x.unit_type==="SECTION_BATCH"),[units]),courses=useMemo(()=>units.filter(x=>x.unit_type==="COURSE"),[units]),parents=useMemo(()=>users.filter(x=>x.role==="Parent / Guardian"&&x.is_active),[users]);
 async function submit(e){e.preventDefault();try{setSaving(true);setError("");const payload={...form,campus_id:Number(form.campus_id),program_unit_id:Number(form.program_unit_id),section_unit_id:form.section_unit_id?Number(form.section_unit_id):null,parent_user_id:form.parent_user_id?Number(form.parent_user_id):null,course_unit_ids:form.course_unit_ids.map(Number)};const r=await api.post("/api/v1/admissions/enroll-student",payload);setMessage(r.data.name+" enrolled successfully.");loadStudents();setForm({name:"",email:"",password:"",campus_id:1,program_unit_id:"",section_unit_id:"",course_unit_ids:[],parent_user_id:"",relationship:"Guardian"})}catch(e){setError(e?.response?.data?.detail||"Unable to enroll student.")}finally{setSaving(false)}}
 const filtered=students.filter(x=>{
  const text=(x.name+" "+x.email+" "+x.status).toLowerCase().includes(query.toLowerCase());
  const hasSection=x.assignments.some(a=>a.assignment_type==="SECTION_ASSIGNMENT");
  if(!text)return false;
  if(qualityFilter==="ACTIVE")return x.status==="Active";
  if(qualityFilter==="WITHDRAWN")return x.status==="Withdrawn";
  if(qualityFilter==="NO_SECTION")return !hasSection;
  if(qualityFilter==="NO_GUARDIAN")return x.has_guardian===false;
  return true;
 });
 async function changeSection(id,section_unit_id){try{await api.patch("/api/v1/admissions/students/"+id,{section_unit_id:Number(section_unit_id)});setMessage("Section updated.");loadStudents()}catch(e){setError(e?.response?.data?.detail||"Unable to update section.")}}
 async function linkGuardian(studentId){const parentId=guardianDraft[studentId];if(!parentId){setError("Select a parent or guardian first.");return}try{setError("");await api.post("/api/v1/admin/parent-student-links",{parent_user_id:Number(parentId),student_user_id:studentId,relationship:"Guardian"});setMessage("Parent / Guardian linked successfully.");setGuardianDraft(x=>({...x,[studentId]:""}));await loadStudents()}catch(e){setError(e?.response?.data?.detail||"Unable to link parent or guardian.")}}
 async function viewProfile(student){try{setProfileLoading(true);setError("");const r=await api.get("/api/v1/admissions/students/"+student.id+"/profile");setProfile(r.data)}catch(e){setError(e?.response?.data?.detail||"Unable to load student profile.")}finally{setProfileLoading(false)}}
 async function viewHistory(student){try{setHistoryStudent(student);setHistoryLoading(true);setError("");const r=await api.get("/api/v1/admissions/students/"+student.id+"/history");setHistory(r.data)}catch(e){setError(e?.response?.data?.detail||"Unable to load enrollment history.");setHistory([])}finally{setHistoryLoading(false)}}
 async function changeStatus(id,status){if(status==="Withdrawn"&&!window.confirm("Withdraw this student? The account will become inactive."))return;try{await api.patch("/api/v1/admissions/students/"+id,{status});setMessage("Enrollment status updated.");loadStudents()}catch(e){setError(e?.response?.data?.detail||"Unable to update status.")}}
 return <div className="workspace-page"><div className="page-heading"><div><span className="eyebrow">Admissions</span><h1>Student Enrollment</h1><p>Create the student account and academic enrollment in one workflow.</p></div></div>{error&&<div className="error-banner">{error}</div>}{message&&<div className="success-banner">{message}</div>}
 <section className="panel"><div className="admissions-tabs">{[["DASHBOARD","Dashboard"],["NEW","New Admission"],["STUDENTS","Students"],["EXCEPTIONS","Exceptions"],["HISTORY","History"]].map(([key,label])=><button type="button" key={key} className={admissionView===key?"primary":"table-action"} onClick={()=>{setAdmissionView(key);if(key==="EXCEPTIONS")setQualityFilter("NO_SECTION");if(key==="STUDENTS")setQualityFilter("ALL")}}>{label}</button>)}</div></section>
 {admissionView==="DASHBOARD"&&<section className="kpi-grid"><button type="button" className="kpi-card" onClick={()=>setQualityFilter("ALL")}><small>Total Students</small><strong>{summary.total}</strong></button><button type="button" className="kpi-card" onClick={()=>setQualityFilter("ACTIVE")}><small>Active</small><strong>{summary.active}</strong></button><button type="button" className="kpi-card" onClick={()=>setQualityFilter("WITHDRAWN")}><small>Withdrawn</small><strong>{summary.withdrawn}</strong></button><button type="button" className="kpi-card" onClick={()=>setQualityFilter("NO_SECTION")}><small>{labels.missing}</small><strong>{summary.without_section}</strong></button><button type="button" className="kpi-card" onClick={()=>setQualityFilter("NO_GUARDIAN")}><small>Without Parent / Guardian</small><strong>{summary.without_guardian}</strong></button></section>}
 {admissionView==="DASHBOARD"&&<section className="panel"><div className="panel-title"><b>Admissions Overview</b><span>Use the sections above to manage the admission lifecycle</span></div><div className="detail-grid"><div><small>New Admission</small><strong>Create student + academic enrollment</strong></div><div><small>Students</small><strong>Profiles, sections and status</strong></div><div><small>Exceptions</small><strong>Fix missing section or guardian data</strong></div><div><small>History</small><strong>Open a student's timeline from Students</strong></div></div></section>}
 {admissionView==="NEW"&&<section className="panel"><form className="setup-form" onSubmit={submit}><label>Student Name<input required value={form.name} onChange={e=>setForm(x=>({...x,name:e.target.value}))}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm(x=>({...x,email:e.target.value}))}/></label><label>Temporary Password<input required type="password" minLength="8" value={form.password} onChange={e=>setForm(x=>({...x,password:e.target.value}))}/></label><label>Campus ID<input required type="number" min="1" value={form.campus_id} onChange={e=>setForm(x=>({...x,campus_id:e.target.value}))}/></label>
 <label>{labels.program}<select required value={form.program_unit_id} onChange={e=>setForm(x=>({...x,program_unit_id:e.target.value}))}><option value="">Select</option>{programs.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>{labels.section}<select value={form.section_unit_id} onChange={e=>setForm(x=>({...x,section_unit_id:e.target.value}))}><option value="">Optional</option>{sections.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <label>{labels.courses}<select multiple value={form.course_unit_ids} onChange={e=>setForm(x=>({...x,course_unit_ids:Array.from(e.target.selectedOptions,o=>o.value)}))}>{courses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><small>Use Ctrl/Cmd to select multiple courses.</small></label><label>{labels.guardian}<select value={form.parent_user_id} onChange={e=>setForm(x=>({...x,parent_user_id:e.target.value}))}><option value="">Link later</option>{parents.map(x=><option key={x.id} value={x.id}>{x.name} — {x.email}</option>)}</select></label><label>Relationship<input value={form.relationship} onChange={e=>setForm(x=>({...x,relationship:e.target.value}))}/></label><button className="primary" disabled={saving}>{saving?"Enrolling...":"Enroll Student"}</button></form></section>}
 {(admissionView==="STUDENTS"||admissionView==="EXCEPTIONS")&&<section className="panel"><div className="panel-title"><b>Enrolled Students</b><span>{filtered.length} shown · {students.length} total</span></div>{qualityFilter!=="ALL"&&<div className="filter-banner">Filter: {qualityFilter.replaceAll("_"," ")} <button className="table-action" onClick={()=>setQualityFilter("ALL")}>Clear</button></div>}<input className="search-input" placeholder="Search student" value={query} onChange={e=>setQuery(e.target.value)}/><div className="table-scroll"><table><thead><tr><th>Student</th><th>{labels.assignment}</th><th>{labels.section}</th><th>Status</th><th>Parent / Guardian</th><th>Details</th><th>History</th></tr></thead><tbody>{filtered.length?filtered.map(s=><tr key={s.id}><td>{s.name}<br/><small>{s.email}</small></td><td>{s.assignments.filter(a=>a.assignment_type!=="SECTION_ASSIGNMENT").map(a=><div key={a.id}>{a.unit_name} <small>({a.assignment_type.replaceAll("_"," ")})</small></div>)}</td><td><select value={s.assignments.find(a=>a.assignment_type==="SECTION_ASSIGNMENT")?.unit_id||""} onChange={e=>e.target.value&&changeSection(s.id,e.target.value)}><option value="">Not assigned</option>{sections.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></td><td><select value={s.status} onChange={e=>changeStatus(s.id,e.target.value)}><option>Active</option><option>Withdrawn</option></select></td><td>{s.has_guardian?<span>Linked</span>:<div><select value={guardianDraft[s.id]||""} onChange={e=>setGuardianDraft(x=>({...x,[s.id]:e.target.value}))}><option value="">Select guardian</option>{parents.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button type="button" className="table-action" onClick={()=>linkGuardian(s.id)}>Link</button></div>}</td><td><button className="table-action" onClick={()=>viewProfile(s)}>View Profile</button></td><td><button className="table-action" onClick={()=>viewHistory(s)}>View History</button></td></tr>):<tr><td colSpan="7" className="empty-cell">No students found.</td></tr>}</tbody></table></div></section>}
 {profile&&<section className="panel"><div className="panel-title"><b>Student Profile — {profile.name}</b><button className="table-action" onClick={()=>setProfile(null)}>Close</button></div>{profileLoading?<p>Loading profile...</p>:<div className="detail-grid"><div><small>Email</small><strong>{profile.email}</strong></div><div><small>Campus</small><strong>{profile.campus_id}</strong></div><div><small>Status</small><strong>{profile.status}</strong></div><div><small>History Events</small><strong>{profile.history_count}</strong></div><div><small>Academic Enrollment</small>{profile.academics.length?profile.academics.map((a,i)=><div key={i}><strong>{a.unit_name}</strong> <small>{a.assignment_type.replaceAll("_"," ")}</small></div>):<strong>Not assigned</strong>}</div><div><small>{labels.guardian}</small>{profile.guardians.length?profile.guardians.map(g=><div key={g.id}><strong>{g.name}</strong><br/><small>{g.relationship} · {g.email} · {g.is_active?"Active":"Inactive"}</small></div>):<strong>Not linked</strong>}</div></div>}</section>}
 {(admissionView==="HISTORY"||historyStudent)&&historyStudent&&<section className="panel"><div className="panel-title"><b>Enrollment History — {historyStudent.name}</b><button className="table-action" onClick={()=>{setHistoryStudent(null);setHistory([])}}>Close</button></div>
 {historyLoading?<p>Loading history...</p>:history.length?<div className="table-scroll"><table><thead><tr><th>Date / Time</th><th>Event</th><th>From</th><th>To</th><th>Changed By</th><th>Details</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{new Date(h.created_at).toLocaleString()}</td><td>{h.event_type.replaceAll("_"," ")}</td><td>{h.from_unit||"—"}</td><td>{h.to_unit||"—"}</td><td>{h.actor}</td><td>{h.details||"—"}</td></tr>)}</tbody></table></div>:<div className="empty-cell">No enrollment history recorded yet.</div>}</section>}
 </div>;
}
