import React,{useEffect,useState} from "react"; import {api} from "../api";
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
const FINANCE_UI={School:{title:"My School Fees",fee:"School Fee",description:"View tuition, term, transport and other school fee balances and receipts."},College:{title:"My Semester Fees",fee:"College Fee",description:"View tuition, semester, exam and laboratory fee balances and receipts."},University:{title:"My University Fees",fee:"University Fee",description:"View tuition, credit, hostel and other academic fee balances and receipts."}};
export default function StudentFinance({ui}){
 const labels=FINANCE_UI[ui?.label]||FINANCE_UI.University;
 const [rows,setRows]=useState([]),[receipts,setReceipts]=useState([]),[err,setErr]=useState("");
 useEffect(()=>{api.get("/api/v1/fee-ledger").then(r=>setRows(r.data)).catch(e=>setErr(e?.response?.data?.detail||"Unable to load fees."))},[]);
 const due=rows.reduce((s,r)=>s+r.amount_due,0),paid=rows.reduce((s,r)=>s+r.amount_paid,0),balance=rows.reduce((s,r)=>s+r.balance,0);
 async function showReceipts(id){try{const r=await api.get("/api/v1/fee-ledger/"+id+"/receipts");setReceipts(r.data);setErr("")}catch(e){setErr(e?.response?.data?.detail||"Unable to load receipts.")}}
 return <div><div className="page-title"><div><span className="eyebrow">{ui.label} Student Finance</span><h1>{labels.title}</h1><p>{labels.description}</p></div></div>{err&&<div className="error">{err}</div>}<div className="finance-kpis"><article><small>Total Fees</small><strong>{money(due)}</strong></article><article><small>Paid</small><strong>{money(paid)}</strong></article><article><small>Balance</small><strong>{money(balance)}</strong></article></div><section className="panel structure-table"><div className="table-scroll"><table><thead><tr><th>{labels.fee}</th><th>Due</th><th>Paid</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td><b>{r.title}</b><br/><small>{r.fee_code}</small></td><td>{money(r.amount_due)}</td><td>{money(r.amount_paid)}</td><td>{money(r.balance)}</td><td>{r.status}</td><td><button className="table-action" onClick={()=>showReceipts(r.id)}>Receipts</button></td></tr>):<tr><td colSpan="6" className="empty-cell">No fee assignments available.</td></tr>}</tbody></table></div></section>{receipts.length>0&&<section className="panel structure-table"><div className="panel-title"><b>Receipts</b><span>{receipts.length}</span></div><div className="table-scroll"><table><thead><tr><th>Receipt</th><th>Amount</th><th>Reference</th><th>Paid At</th></tr></thead><tbody>{receipts.map(x=><tr key={x.id}><td>{x.receipt_no}</td><td>{money(x.amount)}</td><td>{x.reference||"—"}</td><td>{new Date(x.paid_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>}</div>
}